version: '3.8'
services:
  house-finder-360-db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  house-finder-360-app:
    container_name: house-finder-360
    image: ${DOCKER_REGISTRY-}house-finder-360-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"