version: '3.8'
services:
  housefinder360app:
    container_name: house-finder-360
    image: ${DOCKER_REGISTRY-}housefinder360app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    