version: '3.8'
services:
  house-finder-360-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
  house-finder-360-app:
    container_name: house-finder-360
    image: ${DOCKER_REGISTRY-}house-finder-360-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: on-failure
    environment:
      DATABASE_HOST: "house-finder-360-db"
      DATABASE_PORT: "5432"
      DATABASE_SCHEMA: "postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
    depends_on:
      - house-finder-360-db
      